DROP TABLE heartbeat;
DROP TABLE reconciliation_custody_cursors;
DROP TABLE reconciliation_deposit_cursors;
DROP TABLE reconciliation_blocks;
DROP TABLE reconciliation_findings;
DROP TABLE audit;
DROP TABLE idempotency_keys;
DROP TABLE webhook_deliveries;
DROP TABLE events;
DROP TABLE webhook_endpoints;
DROP TABLE refund_payment_claims;
DROP FUNCTION enforce_refund_payment_claim_capacity();
DROP TABLE refunds;
DROP TABLE transitions;
ALTER TABLE quotes DROP CONSTRAINT quotes_consumed_by_fkey;
DROP TABLE deposits;
DROP TABLE flush_exclusions;
DROP TABLE flushed;
DROP TABLE flushes;
DROP TABLE pending_transfers;
DROP TABLE cursors;
DROP TABLE addresses;
DROP TABLE quotes;
DROP TABLE customers;
DROP TABLE seen_signatures;
DROP TABLE route_pauses;
DROP TABLE treasuries;
DROP TABLE request_signing_keys;
DROP TABLE api_keys;
DROP TABLE permissions;
DROP TABLE sessions;
DROP TABLE invitations;
DROP TABLE memberships;
DROP TABLE recovery_codes;
DROP TABLE passkeys;
DROP TABLE identities;
DROP TABLE users;
DROP TABLE account_limits;
DROP TABLE confirmation_policies;
DROP TABLE accounts;
DROP FUNCTION reject_append_only_mutation();

REVOKE SELECT ON TABLE _sqlx_migrations FROM topup_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
    REVOKE SELECT, INSERT, UPDATE, DELETE ON TABLES FROM topup_app;
REVOKE USAGE ON SCHEMA public FROM topup_app;
DROP ROLE IF EXISTS topup_app;
