//! Cross-language checks against vectors generated by the Foundry contracts.

#![allow(clippy::expect_used, clippy::indexing_slicing)]

use std::error::Error;
use std::str::FromStr;

use alloy_primitives::{Address, B256};
use serde::Deserialize;
use topup_core::address::{forwarder_address, lock_salt, persistent_salt};

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct Vectors {
    factory: String,
    implementation: String,
    predicted_addresses: Vec<String>,
    salts: Vec<String>,
    persistent: Vec<PersistentVector>,
    lock: Vec<LockVector>,
}

#[derive(Deserialize)]
struct PersistentVector {
    product_slug: String,
    external_id: String,
    version: u64,
    salt: String,
    predicted_address: String,
}

#[derive(Deserialize)]
struct LockVector {
    product_slug: String,
    external_id: String,
    lock_ref: String,
    salt: String,
    predicted_address: String,
}

#[test]
fn reproduces_all_foundry_create2_vectors() -> Result<(), Box<dyn Error>> {
    let vectors: Vectors =
        serde_json::from_str(include_str!("../../../contracts/test-vectors/create2.json"))?;
    let factory = Address::from_str(&vectors.factory)?;
    let implementation = Address::from_str(&vectors.implementation)?;

    assert_eq!(vectors.salts.len(), vectors.predicted_addresses.len());
    for (salt, expected) in vectors.salts.iter().zip(&vectors.predicted_addresses) {
        assert_eq!(
            forwarder_address(factory, implementation, B256::from_str(salt)?),
            Address::from_str(expected)?
        );
    }

    for vector in vectors.persistent {
        let salt = persistent_salt(&vector.product_slug, &vector.external_id, vector.version);
        assert_eq!(salt, B256::from_str(&vector.salt)?);
        assert_eq!(
            forwarder_address(factory, implementation, salt),
            Address::from_str(&vector.predicted_address)?
        );
    }

    for vector in vectors.lock {
        let salt = lock_salt(&vector.product_slug, &vector.external_id, &vector.lock_ref);
        assert_eq!(salt, B256::from_str(&vector.salt)?);
        assert_eq!(
            forwarder_address(factory, implementation, salt),
            Address::from_str(&vector.predicted_address)?
        );
    }

    Ok(())
}
