//! Cross-language checks against vectors generated by the Foundry contracts
//! (`contracts/script/GenerateCreate2Vectors.s.sol`).

#![allow(clippy::expect_used, clippy::indexing_slicing)]

use std::error::Error;
use std::str::FromStr;

use alloy_primitives::{Address, B256};
use serde::Deserialize;
use topup_core::address::{deposit_address_salt, forwarder_address, quote_salt};

#[derive(Deserialize)]
struct Vectors {
    factory: String,
    implementation: String,
    forwarders: Vec<ForwarderVector>,
    quote: Vec<QuoteVector>,
    deposit_address: Vec<DepositAddressVector>,
}

#[derive(Deserialize)]
struct ForwarderVector {
    treasury: String,
    salt: String,
    predicted_address: String,
}

#[derive(Deserialize)]
struct QuoteVector {
    account: String,
    client_reference_id: String,
    quote_id: String,
    treasury: String,
    salt: String,
    predicted_address: String,
}

#[derive(Deserialize)]
struct DepositAddressVector {
    account: String,
    livemode: bool,
    client_reference_id: String,
    version: u64,
    treasury: String,
    salt: String,
    predicted_address: String,
}

#[test]
fn reproduces_all_foundry_create2_vectors() -> Result<(), Box<dyn Error>> {
    let vectors: Vectors =
        serde_json::from_str(include_str!("../../../contracts/test-vectors/create2.json"))?;
    let factory = Address::from_str(&vectors.factory)?;
    let implementation = Address::from_str(&vectors.implementation)?;

    assert!(!vectors.forwarders.is_empty());
    for vector in &vectors.forwarders {
        assert_eq!(
            forwarder_address(
                factory,
                implementation,
                Address::from_str(&vector.treasury)?,
                B256::from_str(&vector.salt)?
            ),
            Address::from_str(&vector.predicted_address)?
        );
    }

    assert!(!vectors.quote.is_empty());
    for vector in vectors.quote {
        let salt = quote_salt(
            &vector.account,
            &vector.client_reference_id,
            &vector.quote_id,
        );
        assert_eq!(salt, B256::from_str(&vector.salt)?);
        assert_eq!(
            forwarder_address(
                factory,
                implementation,
                Address::from_str(&vector.treasury)?,
                salt
            ),
            Address::from_str(&vector.predicted_address)?
        );
    }

    assert!(!vectors.deposit_address.is_empty());
    for vector in vectors.deposit_address {
        let salt = deposit_address_salt(
            &vector.account,
            vector.livemode,
            &vector.client_reference_id,
            vector.version,
        );
        assert_eq!(salt, B256::from_str(&vector.salt)?);
        assert_eq!(
            forwarder_address(
                factory,
                implementation,
                Address::from_str(&vector.treasury)?,
                salt
            ),
            Address::from_str(&vector.predicted_address)?
        );
    }

    Ok(())
}
